### ISSUE TITLE
Document the AWS IAM policy document 

### ISSUE THREAD

**Issue by timperrett** [buildkite/buildkite-agent-scaler#1]
It would be great if the readme specified what IAM policy document was needed to run this lambda. One can figure it out by trial and error, but its a little tedious for new users :-)

**Comment by toolmantim** [comment]
That's a good idea @timperrett!

Did you by any chance figure it out? If you have it handy, it'd make it super easy to update the readme. If not, no problems!

**Comment by timperrett** [comment]
I didn’t actually look that closely just yet :-) if I spend time on it tomorrow I’ll send a PR

**Comment by lox** [comment]
Documented in https://github.com/buildkite/buildkite-agent-scaler#running-as-an-aws-lambda!
