### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by worxli** [buildkite/buildkite-agent-scaler#2]
I just stumbled upon this project and it seems interesting even though it claims to be experimental.
* Is this project actively developed?
* And can it be used to scale AWS instances or what is your plan with this project?

**Comment by lox** [comment]
Still an experiment @worxli, but hoping it will work out well and become an integral part of https://github.com/buildkite/elastic-ci-stack-for-aws.

The plan at this stage is for using it to scale ASG's only.
