### ISSUE TITLE
Suspected typo in lambda configuration

### ISSUE THREAD

**Issue by amu-g** [buildkite/buildkite-agent-scaler#21]
Hey,

I believe there is a typo in the env var that the lambda reads for configuration. Currently, one variable controls the lambdas interval AND the lambdas timeout: 

https://github.com/buildkite/buildkite-agent-scaler/blob/02292a7f8aa5f853c4b48f929f261582e690a7be/lambda/main.go#L54-L66

These two variable were controlled with two env var prior to #13 :

https://github.com/buildkite/buildkite-agent-scaler/blob/dfd3df82bdb787ac6ec88561a499882dea937310/lambda/main.go#L46-L60

Looks like a refactor with an accidental copy paste error?

**Comment by eculver** [comment]
Looks like this is fixed? Should this ticket be closed too?

**Comment by pda** [comment]
Yep, thanks @eculver and @amu-g 👍🏼
