### ISSUE TITLE
buildkite-agent-scaler v1.0.1 release not in S3 bucket at expected key.

### ISSUE THREAD

**Issue by rebej** [buildkite/buildkite-agent-scaler#24]
The v1.0.1 autoscaler doesn't seem to be in the same s3 location as the other releases. The 
https://s3.amazonaws.com/buildkite-lambdas/buildkite-agent-scaler/v1.0.1/handler.zip url has an access denied error where the previous releases are available at same url can be accessed (e.g. https://s3.amazonaws.com/buildkite-lambdas/buildkite-agent-scaler/v1.0.0/handler.zip)

**Comment by pda** [comment]
Thanks for the heads up @rebej. I’ll look into this later today.

**Comment by pmenglund** [comment]
@pda did you forget to check? 😉 It is still not accessible...

**Comment by rebej** [comment]
Bump

**Comment by pda** [comment]
Sorry, I completely dropped this, and just stumbled upon it today.
I've sorted it out now; v1.0.1 is on https://github.com/buildkite/buildkite-agent-scaler/releases/tag/v1.0.1 and in all the usual S3 buckets (per region).
