### ISSUE TITLE
ScaleOutFactor * number of jobs cannot be greater than MaxSize or no agents will be scaled out

### ISSUE THREAD

**Issue by nitrocode** [buildkite/buildkite-agent-scaler#34]
I was wondering why I wasn't seeing any agents. I went to the lambda's cloudwatch logs and saw this.

```
2020-10-06T17:47:13.030-04:00 | 2020/10/06 21:47:13 👮‍️ Increasing scale-out of 8 by factor of 2.00
2020-10-06T17:47:13.030-04:00 | 2020/10/06 21:47:13 Scaling OUT 📈 to 16 instances (currently 0)
2020-10-06T17:47:13.142-04:00 | 2020/10/06 21:47:13 Scaling error: ValidationError: New SetDesiredCapacity value 16 is above max value 10 for the AutoScalingGroup.
```

This looks like an error in the lambda scaler. If this scaler hits a max, instead of failing to scale out any agents, it should scale to the `MaxSize` set on the asg.

https://github.com/buildkite/buildkite-agent-scaler/blob/12d9dfb124c6c66245e58d61ee4bd6e969ab11ad/scaler/scaler.go#L226-L229

**Comment by yob** [comment]
I've transferred this over to the scaler repo, where the fix would be required.

We *think* the solution might be to clamp the scale up logic to `min(MaxSize, newDesiredSize)`

**Comment by nitrocode** [comment]
That sounds like it would work.

One other issue i noticed is that the lambda output returned a 0 return code because cloudwatch shows all successful runs. This makes it difficult to monitor for these types of errors. The lambda should not only return the error, as it already does, but also return a non-zero error code.
