### ISSUE TITLE
support mac1.metal instances on AWS

### ISSUE THREAD

**Issue by OliverKoo** [buildkite/buildkite-agent-scaler#43]
I am using the buildkite agent scalar lambda function with my ASG on my mac ec2 instances. Trying to implement [gracefully scaling in ](disconnect-after-idle-timeout) using `--disconnect-after-idle-timeout` and [`PostStop` systemd script](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/00c45ab47160b1d1d44c0b3bea8456456444c60e/packer/linux/conf/bin/bk-install-elastic-stack.sh#L136-L143). 

However mac os [launchd does not have an equivalent of `ExecStopPost`](https://apple.stackexchange.com/questions/398678/launchd-launchctl-pre-and-post-scripting). Do any of you know a workaround? Currently I am planning to just have ~/Library/LaunchAgents/com.buildkite.buildkite-agent.plist call a wrapper script 
```
#!/bin/bash
/usr/local/bin/buildkite-agent start

wait

/usr/local/bin/terminate-instance
/usr/bin/sudo shutdown -h now
```

I think there is probably a more elegant way of doing this. Are any of you run into the same issue and came up with a proper solution?

**Comment by yob** [comment]
Thanks @OliverKoo. I think the scaler is likely to be agnostic about the instance type, it's solely focused on adjusting the ASG desired size based on metrics available from Buildkite.

If it's OK I might close this and and consolidate the discussion in https://github.com/buildkite/elastic-ci-stack-for-aws/issues/776
