### ISSUE TITLE
Generated ExecutionRole doesn't grant access to agent token in secrets manager

### ISSUE THREAD

**Issue by ChrisLane** [buildkite/buildkite-agent-scaler#65]
I've just tried to spin up a buildkite agent using elastic-ci-stack-for-aws v5.9.0 and noticed that I don't have any working instances after.

- I'm keeping my buildkite agent token in a secrets manager secret named `/psa1/buildkite-agent-token`.
- In the AutoScalingFunction cloudwatch logs I see `buildkite-agent-scaler version 1.1.3 dev` `ValidationException: An error occurred while calling one AWS dependency service. status code: 400, requestError: null` repeatedly
- In CloudTrail I see the following:
```
User: arn:aws:sts::{account}:assumed-role/buildkite-buil-ExecutionRole-5E6UIEE7DXY3/buildkite-ps-AutoscalingFunction-ez63yCXb1Bii is not authorized to perform: secretsmanager:GetSecretValue on resource: /psa1/buildkite-agent-token because no identity-based policy allows the secretsmanager:GetSecretValue action
```

I've granted the buildkite-agent-Role secrets manager access but from what I can see, there's no way to do the same for the auto-generated autoscaling function role which leads me to believe this may be a bug.

The buildkite docs state that a policy statement should be added to the secret to allow access but this cannot be expected for AWS CDK where such steps should be automated.

I tried working around this by importing the `ExecutionRoleName` output from the autoscaling stack into my own CDK stack but this wasn't possible since the output is not named.

**Comment by moskyb** [comment]
hey chris! it looks like the secrets manager integration advice we have published at https://buildkite.com/docs/agent/v3/aws/secrets-manager leads to an awkward iam scenario, which isn't ideal. you certainly shouldn't need to manually update a resource policy to track a dynamic role name.

rather than adding more parameters for custom iam policies for the elastic stack to pass through to the agent-scaler stack, we're keen to double down on our support for KMS-encrypted secrets in SSM Parameter Store, and remove the page regarding Secrets Manager integration / pass-through.

in our experience, parameter store is just as secure and effective (and cheaper) than secrets manager for this use-case, so hopefully that applies to your use-case too.

**Comment by ChrisLane** [comment]
Thanks for the response.

Given that it's intentionally not possible to create encrypted SSM parameters via AWS CDK, I doubt AWS will continue to support them much longer.
Amazon have gone all in on recommending Secrets Manager.


On 29 Jun 2022, 06:21, at 06:21, Ben Moskovitz ***@***.***> wrote:
>hey chris! it looks like the secrets manager integration advice we have
>published at https://buildkite.com/docs/agent/v3/aws/secrets-manager
>leads to an awkward iam scenario, which isn't ideal. you certainly
>shouldn't need to manually update a resource policy to track a dynamic
>role name.
>
>rather than adding more parameters for custom iam policies for the
>elastic stack to pass through to the agent-scaler stack, we're keen to
>double down on our support for KMS-encrypted secrets in SSM Parameter
>Store, and remove the page regarding Secrets Manager integration /
>pass-through.
>
>in our experience, parameter store is just as secure and effective (and
>cheaper) than secrets manager for this use-case, so hopefully that
>applies to your use-case too.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/buildkite/buildkite-agent-scaler/issues/65#issuecomment-1169545616
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by ChrisLane** [comment]
For anyone coming across this, it seems like the manual step of attaching a policy to grant access to the SSM secret to the ExecutionRole may no longer be necessary if you add the policy ARN in the `ScalerManagedPolicyARNs` elastic stack parameter.
