### ISSUE TITLE
Desired capacity does not account for running jobs

### ISSUE THREAD

**Issue by etaoins** [buildkite/buildkite-agent-scaler#7]
Unless I'm misunderstanding, it appears that autoscaling doesn't not account for currently running jobs. For example, in this situation:

1. One scheduled job
2. One running job
3. One running agent

We think our desired capacity should be 1 when it should actually scale up to 2.

Let me know if I'm understanding this correctly and I'll open a PR.

**Comment by lox** [comment]
I believe you are correct @etaoins!
