### ISSUE TITLE
Scaler seems to bypass Lifecycle Hooks

### ISSUE THREAD

**Issue by lox** [buildkite/buildkite-agent-scaler#8]
In my initial testing, it looks like lifecycle hooks didn't seem to be triggered on scale-ins 🤔

@etaoins have you noticed that?

**Comment by etaoins** [comment]
It appeared to work for me but due to #6 and #7 the ASG always wanted to scale in. I had an agent terminate between two jobs in the same build but never while I job was running. That could’ve just been luck, though.

**Comment by lox** [comment]
Just did some testing and not seeing lifecycle events firing. I suspect that lifecycle hooks only fire when there are autoscaling rules on an ASG.

**Comment by lox** [comment]
I wonder if we could use target tracking to scale-in, but use the lamba for scale-out 🤔

**Comment by lucas044** [comment]
Is this issue relevant anymore with the new version? @lox

**Comment by lox** [comment]
It is in the sense that it's still a thing if you try and use the scale-in support in the lambda, but we disable it in Elastic Stack.

I'd still love to know why it doesn't work.

**Comment by keithduncan** [comment]
This appears to have been fixed some time between last being looked at and now.

In https://github.com/buildkite/elastic-ci-stack-for-aws/pull/964 I’m looking at re-enabling scale in (set desired count to less than current) in the Lambda and using service-side ASG lifecycle hook handlers to orchestrate the agent exit, and the lifecycle hooks are firing:

![Screenshot 2021-11-24 at 09 24 45](https://user-images.githubusercontent.com/22101/143144627-64387b5d-bd1e-4510-b863-1537bc1e29ae.png)
 
:tada:
