### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Amir-Ahmad** [buildkite/buildkite-agent-scaler#89]
Would it be possible to do a new release? I'm waiting for this https://github.com/buildkite/buildkite-agent-scaler/commit/e219eb760b92dd3a665fcd329defab709510797e , but as we're consuming this from the Serverless Application Repository, we need a new release to be able to upgrade.

**Comment by triarius** [comment]
Hi @Amir-Ahmad, a new release (v1.4.0) should be out on the SAR. It should also appear in the next release of the Elastic CI Stack for AWS.

**Comment by Amir-Ahmad** [comment]
> Hi @Amir-Ahmad, a new release (v1.4.0) should be out on the SAR. It should also appear in the next release of the Elastic CI Stack for AWS.

Thanks, appreciate that.
